version: 2
common: &common
  working_directory: ~/rio-tiler
  steps:
    - checkout
    - run:
        name: install dependencies
        command: pip install tox codecov pre-commit --user
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: run pre-commit
        command: |
          if [[ "$CIRCLE_JOB" == "python-3.6" ]]; then
             ~/.local/bin/pre-commit run --all-files
          fi
    - run:
        name: upload coverage report
        command: |
          if [[ "$UPLOAD_COVERAGE" == 1 ]]; then
             ~/.local/bin/coverage xml
             ~/.local/bin/codecov
          fi
        when: always

jobs:
  "python-2.7":
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          - TOXENV=py27

  "python-3.6":
    <<: *common
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36
          - UPLOAD_COVERAGE=1

workflows:
  version: 2
  test:
    jobs:
      - "python-2.7"
      - "python-3.6"
