version: 2
common: &common
  working_directory: ~/rio-tiler
  steps:
    - checkout
    - run:
        name: install dependencies
        command: pip install tox codecov pre-commit --user
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: run pre-commit
        command: |
          if [[ "$CIRCLE_JOB" == "python-3.6" ]]; then
             ~/.local/bin/pre-commit run --all-files
          fi
    - run:
        name: upload coverage report
        command: |
          if [[ "$UPLOAD_COVERAGE" == 1 ]]; then
             ~/.local/bin/coverage xml
             ~/.local/bin/codecov
          fi
        when: always

jobs:
  "python-2.7":
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          - TOXENV=py27

  "python-3.6":
    <<: *common
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36
          - UPLOAD_COVERAGE=1

  "python-3.7":
    <<: *common
    docker:
      - image: circleci/python:3.7.2
        environment:
          - TOXENV=py37

  deploy:
      docker:
        - image: circleci/python:3.7.2
          environment:
            - TOXENV=release
      working_directory: ~/rio-tiler
      steps:
        - checkout
        - run:
            name: verify git tag vs. version
            command: |
              VERSION=$(python -c 'import rio_tiler; print(rio_tiler.__version__)')
              if [ "$VERSION" = "$CIRCLE_TAG" ]; then exit 0; else exit 3; fi
        - run:
            name: install dependencies
            command: pip install tox --user
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USER" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: run tox
            command: ~/.local/bin/tox

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7":
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - "python-3.7"
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
